wafer/talks/urls.py
from django.urls import re_path, include
from rest_framework_extensions import routers

from wafer.talks.views import (
    Speakers, ReviewViewSet, TalkCreate, TalkReview, TalkTypesView, TalkUpdate,
    TalkUrlsViewSet, TalkView, TalkWithdraw, TalksViewSet, TracksView,
    UsersTalks)

router = routers.ExtendedSimpleRouter()

talks_router = router.register(r'talks', TalksViewSet)
talks_router.register(
    r'urls', TalkUrlsViewSet, basename='talks-urls',
    parents_query_lookups=['talk'])
talks_router.register(
    r'reviews', ReviewViewSet, basename='talks-reviews',
    parents_query_lookups=['talk'])

urlpatterns = [
    re_path(r'^$', UsersTalks.as_view(), name='wafer_users_talks'),
    re_path(r'^page/(?P<page>\d+)/$', UsersTalks.as_view(),
        name='wafer_users_talks_page'),
    re_path(r'^new/$', TalkCreate.as_view(), name='wafer_talk_submit'),
    re_path(r'^(?P<pk>\d+)(?:-(?P<slug>[\w-]*))?/$', TalkView.as_view(),
        name='wafer_talk'),
    re_path(r'^(?P<pk>\d+)/edit/$', TalkUpdate.as_view(),
        name='wafer_talk_edit'),
    re_path(r'^(?P<pk>\d+)/review/$', TalkReview.as_view(),
        name='wafer_talk_review'),
    re_path(r'^(?P<pk>\d+)/withdraw/$', TalkWithdraw.as_view(),
        name='wafer_talk_withdraw'),
    re_path(r'^speakers/$', Speakers.as_view(), name='wafer_talks_speakers'),
    re_path(r'^tracks/', TracksView.as_view(), name='wafer_talk_tracks'),
    re_path(r'^types/', TalkTypesView.as_view(), name='wafer_talk_types'),
    re_path(r'^api/', include(router.urls)),
]

wafer/urls.py
from django.urls import include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    re_path(r'^accounts/', include('wafer.registration.urls')),
    re_path(r'^users/', include('wafer.users.urls')),
    re_path(r'^talks/', include('wafer.talks.urls')),
    re_path(r'^sponsors/', include('wafer.sponsors.urls')),
    re_path(r'^pages/', include('wafer.pages.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^markitup/', include('markitup.urls')),
    re_path(r'^schedule/', include('wafer.schedule.urls')),
    re_path(r'^tickets/', include('wafer.tickets.urls')),
    re_path(r'^kv/', include('wafer.kv.urls')),
]

# Serve media
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Pages occupy the entire URL space, and must come last
urlpatterns.append(re_path(r'', include('wafer.pages.urls')))

wafer/talks/models.py
from django.conf import settings
from django.core import validators
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse
from django.utils.functional import lazy
from django.utils.text import format_lazy
from django.utils.translation import gettext, gettext_lazy as _
from django.utils.timezone import now

import reversion
from markitup.fields import MarkupField
from reversion.models import Version

from wafer.kv.models import KeyValue


# constants to make things clearer elsewhere
SUBMITTED = 'S'
UNDER_CONSIDERATION = 'U'
PROVISIONAL = 'P'
ACCEPTED = 'A'
REJECTED = 'R'
CANCELLED = 'C'
WITHDRAWN = 'W'


# Utility functions used in the forms
# We define this here, rather than in the users model, to avoid import
# loops as we need to import talks into users
def render_author(author):
    return '%s (%s)' % (author.userprofile.display_name(), author)


def authors_help():
    _ = gettext  # This function will be wrapped for lazy evaluation
    text = []
    text.append(_("The speakers presenting the talk."))
    if not settings.WAFER_PUBLIC_ATTENDEE_LIST:
        text.append(_(
            "To ensure attendee privacy, you will only be able to see "
            "yourself and authors that have been added to the talk by the "
            "conference organisers. "
            "If you will have other co-authors, add a note in the notes "
            "field, so the organisers can add them to your talk."
        ))
    text.append(_(
        "<strong>You, as the talk submitter, will be the talk's corresponding "
        "author.</strong>"
    ))
    return ' '.join(text)


class TalkTypeManager(models.Manager):

    def open_for_submission(self):
        Q = models.Q
        return self.filter(
            Q(disable_submission=False) &
            (
                Q(submission_deadline__isnull=True) |
                Q(submission_deadline__gt=now()) |
                Q(accept_late_submissions=True)
            )
        )


class TalkType(models.Model):
    """A type of talk."""
    name = models.CharField(_('name'), max_length=255)
    description = models.TextField(_('description'), max_length=1024)
    order = models.IntegerField(_('order'), default=1)
    disable_submission = models.BooleanField(
        _('disable submission'),
        default=False,
        help_text="Don't allow users to submit talks of this type.")
    submission_deadline = models.DateTimeField(
        _('submission deadline'),
        null=True,
        blank=True,
        help_text=_("Deadline for submitting talks of this type")
    )
    accept_late_submissions = models.BooleanField(
        _('accept late submissions'),
        default=False,
        help_text=_("Whether submissions after the deadline should be accepted")
    )
    show_speakers = models.BooleanField(
        _('Show authors in speakers list'),
        default=True,
        help_text=_("Whether to show the authors for this talk type in the speakers list")
    )
    show_pending_submissions = models.BooleanField(
        _('show pending submissions'),
        default=False,
        help_text=_("Whether to publicly show pending submissions, before acceptance")
    )

    objects = TalkTypeManager()

    def __str__(self):
        return u'%s' % (self.name,)

    class Meta:
        ordering = ['order', 'id']
        verbose_name = _('talk type')
        verbose_name_plural = _('talk types')

    def css_class(self):
        """Return a string for use as a css class name"""
        # While css can represent complicated strings
        # using escaping, we want simplicity and obvious predictablity
        return u'talk-type-%s' % slugify(self.name)

    css_class.admin_order_field = 'name'
    css_class.short_description = _('CSS class name')


class Track(models.Model):
    """A conference track."""
    name = models.CharField(_('name'), max_length=255)
    description = models.TextField(_('description'), max_length=1024)
    order = models.IntegerField(_('order'), default=1)

    def __str__(self):
        return u'%s' % (self.name,)

    class Meta:
        ordering = ['order', 'id']
        verbose_name = _('track')
        verbose_name_plural = _('tracks')

    def css_class(self):
        """Return a string for use as a css class name"""
        # While css can represent complicated strings
        # using escaping, we want simplicity and obvious predictablity
        return u'track-%s' % slugify(self.name)

    css_class.admin_order_field = 'name'
    css_class.short_description = _('CSS class name')


@reversion.register(follow=('urls',))
class Talk(models.Model):

    class Meta:
        permissions = (
            ("view_all_talks", "Can see all talks"),
            ("edit_private_notes", "Can edit the private notes fields"),
        )
        verbose_name = _('talk')
        verbose_name_plural = _('talks')

    TALK_STATUS = (
        (ACCEPTED, _('Accepted')),
        (REJECTED, _('Not accepted')),
        (CANCELLED, _('Cancelled')),
        (UNDER_CONSIDERATION, _('Under consideration')),
        (SUBMITTED, _('Submitted')),
        (PROVISIONAL, _('Provisionally Accepted')),
        (WITHDRAWN, _('Withdrawn')),
    )

    talk_id = models.AutoField(primary_key=True)
    talk_type = models.ForeignKey(
        TalkType, verbose_name=_("talk type"), null=True, blank=True, on_delete=models.SET_NULL)
    track = models.ForeignKey(
        Track, verbose_name=_("track"), null=True, blank=True, on_delete=models.SET_NULL)

    LANGUAGES = settings.WAFER_TALK_LANGUAGES
    # DEFAULT_LANGUAGE should be None if WAFER_TALK_LANGUAGES is empty
    DEFAULT_LANGUAGE = LANGUAGES[0][0] if LANGUAGES else None
    language = models.CharField(
        verbose_name=_("language"),
        max_length=5,
        null=True,
        blank=True,
        choices=LANGUAGES,
        default=DEFAULT_LANGUAGE,
    )

    title = models.CharField(_("title"), max_length=1024)

    abstract = MarkupField(
        _("abstract"),
        help_text=_("Write two or three paragraphs describing your talk. "
                    "Who is your audience? What will they get out of it? "
                    "What will you cover?<br />"
                    "You can use Markdown syntax."))

    notes = models.TextField(
        _("notes"),
        null=True, blank=True,
        help_text=_(
            "Any notes for the conference? Such as additional background on "
            "the topic or presenters that isn't going to be published "
            "publicly, special requirements for the event, or thoughts on "
            "scheduling. These are not visible to the public."))

    private_notes = models.TextField(
        _("private notes"),
        null=True, blank=True,
        help_text=_("Note space for the conference organisers (not visible "
                    "to submitter)"))

    status = models.CharField(_('status'), max_length=1, choices=TALK_STATUS,
                              default=SUBMITTED)

    corresponding_author = models.ForeignKey(
        settings.AUTH_USER_MODEL, related_name='contact_talks',
        on_delete=models.CASCADE,
        verbose_name=_("corresponding author"),
        help_text=_(
            "The person submitting the talk (and who questions regarding the "
            "talk should be addressed to)."))

    authors = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name='talks',
        verbose_name=_("authors"),
        help_text=lazy(authors_help, str))

    video = models.BooleanField(
        default=True,
        verbose_name=_("video"),
        help_text=format_lazy(_(
            "By checking this, you are giving permission for the talk to be "
            "videoed, and distributed by the conference, under the "
            '<a href="{license_url}">{license_name} license</a>.'),
            license_url=settings.WAFER_VIDEO_LICENSE_URL,
            license_name=settings.WAFER_VIDEO_LICENSE,
        ),
    )
    video_reviewer = models.EmailField(
        null=True, blank=True,
        verbose_name=_("video reviewer"),
        help_text=_(
            "Email address of a person who will be allowed to review "
            "and approve your video details. "
            "Ideally, a second set of eyes who is not a busy conference "
            "presenter. "
            "But you can specify yourself, if you can't think of anyone else "
            "who would care."
        ))

    kv = models.ManyToManyField(KeyValue)

    submission_time = models.DateTimeField(auto_now_add=True)

    schedule_duplicates = models.IntegerField(
            default=1, validators=[validators.MinValueValidator(0)])

    @property
    def slug(self):
        return slugify(self.title)

    def __str__(self):
        return u'%s: %s' % (self.corresponding_author, self.title)

    def get_absolute_url(self):
        return reverse('wafer_talk', kwargs={
            'pk': self.talk_id,
            'slug': self.slug,
        })

    def get_corresponding_author_contact(self):
        email = self.corresponding_author.email
        profile = self.corresponding_author.userprofile
        if profile.contact_number:
            contact = profile.contact_number
        else:
            # Should we wrap this in a span for styling?
            contact = _('NO CONTACT INFO')
        return '%s - %s' % (email, contact)
    get_corresponding_author_contact.short_description = _('Contact Details')

    def get_corresponding_author_name(self):
        return render_author(self.corresponding_author)

    get_corresponding_author_name.admin_order_field = 'corresponding_author'
    get_corresponding_author_name.short_description = _('Corresponding Author')

    def get_authors_display_name(self):
        authors = list(self.authors.all())
        # Corresponding authors first
        authors.sort(
            key=lambda author: u'' if author == self.corresponding_author

wafer/talks/templates/wafer.talks/review_talk.html
{% extends 'wafer/base_form.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<section class="wafer wafer-talk-review">
  <h1>{% trans "Review Talk" %}</h1>
  {% crispy form %}
</section>
{% endblock %}

wafer/talks/templates/wafer.talks/reviewed-badge.html
{% load i18n %}
{% spaceless %}
  {% if reviewed %}
    {% if review_is_current %}
      <span class="badge bg-success"
            title="{% trans 'Reviewed' %}">
        R: <i class="fas fa-check"></i>
      </span>
    {% else %}
      <span class="badge bg-info"
            title="{% trans 'Reviewed, but outdated (modified since last review)' %}">
        R: <i class="fas fa-clock"></i>
      </span>
    {% endif %}
  {% endif %}
{% endspaceless %}

wafer/talks/templates/wafer.talks/speakers.html
{% extends "wafer/base.html" %}
{% load i18n %}
{% block title %}{% trans "Speakers" %} - {{ WAFER_CONFERENCE_NAME }}{% endblock %}
{% block content %}
<section class="wafer wafer-speakers">
  {% for talk_type, type_rows in speaker_rows.items %}
    {% if talk_type is None %}
      <h1>{% trans 'Speakers' %}</h1>
    {% else %}
      <h1>{% blocktrans %}{{ talk_type }} Speakers{% endblocktrans %}</h1>
    {% endif %}
    {% if talk_type is None %}
      <div class="container speakers-list">
    {% else %}
      <div class="container {{talk_type|slugify}}-speakers-list">
    {% endif %}
      {% for row in type_rows %}
        <div class="row">
          {% for user_profile in row %}
            <div class="col-md-3">
              <div class="wafer-speakers-logo">
                <a href="{% url 'wafer_user_profile' username=user_profile.user.username %}">
                  <img class="thumbnail mx-auto" src="{{ user_profile.avatar_url }}">
                </a>
              </div>
              <div class="wafer-speakers-name">
                <a href="{% url 'wafer_user_profile' username=user_profile.user.username %}">
                  {{ user_profile.display_name }}
                </a>
              </div>
            </div>
          {% endfor %}
        </div>
      {% endfor %}
    </div>
  {% empty %}
    <!-- We show an empty entry wo a) there's some content here and
                                   b) it's easier to check some of the styling -->
    <h1>{% trans 'Speakers' %}</h1>
    <div class="container speakers-list">
        <div class="row">
           <div class="wafer-speakers-name">
              <p>No accepted talks yet</p>
           </div>
        </div>
    </div>
  {% endfor %}
</section>
{% endblock %}

wafer/talks/templates/wafer.talks/talk.html
{% extends "wafer/base.html" %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load static %}
{% block extra_head %}
  {{ block.super }}
  {% if can_review %}
    {{ review_form.media.css }}
  {% endif %}
{% endblock %}
{% block title %}{{ object.title }} - {{ WAFER_CONFERENCE_NAME }}{% endblock %}
{% block content %}
<section class="wafer wafer-talk">
  <h1>
    {{ object.title }}
    {% if can_edit %}
      <a href="{% url 'wafer_talk_edit' object.pk %}"
         class="float-end btn btn-secondary btn-lg d-print-none">{% trans 'Edit' %}</a>
      {% if user.is_staff %}
        <a href="{% url 'admin:talks_talk_change' object.pk %}"
           class="float-end btn btn-secondary btn-lg d-print-none">{% trans 'Admin' %}</a>
      {% endif %}
    {% endif %}
    {% if can_review %}
      <a href="#review" class="float-end btn btn-secondary btn-lg" data-bs-toggle="collapse" data-bs-target="#review">{% trans 'Review' %}</a>
    {% endif %}
  </h1>
  <div>
    <p>
      {% blocktrans trimmed count counter=object.authors.count %}
        Speaker:
      {% plural %}
        Speakers:
      {% endblocktrans %}
      {% for author in object.authors.all %}
        <a href="{% url 'wafer_user_profile' username=author.username %}">{{ author.userprofile.display_name }}</a>
          {% if not forloop.last %}
            &amp;
          {% endif %}
      {% endfor %}
    </p>
    {% if user.is_staff or perms.talks.view_all_talks %}
      {% for author in object.authors.all %}
        <p class="bio">
          {% blocktrans trimmed %}Bio{% endblocktrans %}{% if object.authors.count > 1 %} - {{ author.userprofile.display_name }}{% endif %}:
          {% if author.userprofile.bio %}
            {{ author.userprofile.bio|linebreaks }}
          {% else %}
            <em>{% blocktrans trimmed %}Not provided{% endblocktrans %}</em>
          {% endif %}
        </p>
      {% endfor %}
    {% endif %}

    {% if object.language %}
      <p>
        {% blocktrans trimmed with language=object.get_language_display %}
          Language:
          {{ language }}
        {% endblocktrans %}
      </p>
    {% endif %}
    {% if object.track %}
      <p>
        {% blocktrans trimmed with track=object.track.name %}
          Track:
          {{ track }}
        {% endblocktrans %}
      </p>
    {% endif %}
    <p>
      {% blocktrans trimmed with talk_type=object.talk_type.name|default:_('Talk') %}
        Type:
        {{ talk_type }}
      {% endblocktrans %}
    </p>
    {% if object.get_in_schedule %}
      {% for schedule in object.scheduleitem_set.all %}
        <p>
          {% blocktrans trimmed with venue=schedule.venue %}
            Room:
            {{ venue }}
          {% endblocktrans %}
        </p>
        <p>
          {% blocktrans trimmed with start_time=schedule.get_start_time %}
            Time:
            {{ start_time }}
          {% endblocktrans %}
        </p>
        <p>
          {% blocktrans trimmed with hours=schedule.get_duration.hours|stringformat:"d" minutes=schedule.get_duration.minutes|stringformat:"02d" %}
            Duration:
            {{ hours }}:{{ minutes }}
          {% endblocktrans %}
        </p>
      {% endfor %}
    {% endif %}
  </div>
  {% if user.is_staff or perms.talks.view_all_talks %}
    <div>
      <p>
        {% trans 'Submission:' %}
        {{ object.submission_time }}
        {% if object.is_late_submission %}
          <span class="badge bg-warning ">{% blocktrans trimmed %}Late submission{% endblocktrans %}</span>
        {% endif %}
      </p>
    </div>
    <div>
      <p>
        {% trans 'Status:' %}
        {% if object.submitted %}
          <span class="badge bg-info">{% trans 'Submitted' %}</span>
        {% elif object.under_consideration %}
          <span class="badge bg-info">{% trans 'Under consideration' %}</span>
        {% elif object.provisional %}
          <span class="badge bg-success">{% trans 'Provisionally Accepted' %}</span>
        {% elif object.accepted %}
          <span class="badge bg-success">{% trans 'Accepted' %}</span>
        {% elif object.cancelled %}
          <span class="badge bg-warning">{% trans 'Cancelled' %}</span>
        {% elif object.withdrawn %}
          <span class="badge bg-warning ">{% trans 'Withdrawn' %}</span>
        {% else %}
          <span class="badge bg-danger">{% trans 'Not accepted' %}</span>
        {% endif %}
      </p>
    </div>
  {% endif %}
  <div id="abstract">
    {{ object.abstract }}
  </div>
  {% if perms.talks.view_all_talks or user.is_superuser %}
    {% if talk.notes %}
      <div id="notes" class="card mb-3">
        <div class="card-header">
          {% blocktrans trimmed %}
            <h2>Talk Notes</h2>
            <p>(The following is not visible to attendees.)</p>
          {% endblocktrans %}
        </div>
        <div class="card-body">
          <p class="card-text">
            {{ object.notes|urlize|linebreaksbr }}
          </p>
        </div>
      </div>
    {% endif %}
  {% endif %}
  {% if perms.talks.edit_private_notes and object.private_notes %}
    <div id="private_notes" class="card mb-3">
      <div class="card-header">
        {% blocktrans trimmed %}
          <h2>Private notes</h2>
          <p>(The following is not visible to submitters or attendees.)</p>
        {% endblocktrans %}
      </div>
      <div class="card-body">
        <p class="card-text">
          {{ object.private_notes|urlize|linebreaksbr }}
        </p>
      </div>
    </div>
  {% endif %}
  {% if talk.urls.all %}
    <h3 id="urls_title">{% trans "URLs" %}</h3>
    <ul class="list-group" id="urls">
      {% for talkurl in talk.urls.all %}
        {% if talkurl.public %}
          <li class="list-group-item"><a href="{{ talkurl.url }}">{{ talkurl.description }}</a></li>
        {% endif %}
      {% endfor %}
    </ul>
  {% endif %}
</section>
{% if can_review %}
  <section class="wafer wafer-talk-review collapse" id="review">
    <h2>{% trans 'Review' %}</h2>
    {% crispy review_form %}
  </section>
{% endif %}
{% endblock %}

wafer/talks/templates/wafer.talks/talk_form.html
{% extends 'wafer/base_form.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<section class="wafer wafer-talk-edit">
  {% block heading %}
    {% if can_edit %}
      <h1>{% trans "Edit Talk" %}</h1>
      {% with corresponding_author_name=object.corresponding_author.userprofile.display_name %}
        {% url 'wafer_user_profile' username=object.corresponding_author.username as corresponding_author_url %}
        {% blocktrans trimmed %}
          <p>Submitted by <a href="{{ corresponding_author_url }}">{{ corresponding_author_name }}</a>.</p>
        {% endblocktrans %}
      {% endwith %}
    {% else %}
      <h1>{% trans "Talk Submission" %}</h1>
    {% endif %}
  {% endblock heading %}
  {% if not can_edit and not can_submit %}
    {% block talks_closed %}
      {% blocktrans trimmed %}
        <em>Talk submission is closed</em>
      {% endblocktrans %}
    {% endblock talks_closed %}
  {% else %}
    {% block form_preamble %}
      {% url 'wafer_user_edit_profile' form.user as edit_bio_url %}
      {% if form.user.userprofile.bio %}
        <div>
          <label for="bio" class="col-form-label">
            {% trans "Your Biography" %}
            <a href="{{ edit_bio_url }}">{% trans "Edit" %}</a>
          </label>
          <div id="bio" class="card card-body">
            {{ form.user.userprofile.bio|linebreaks }}
          </div>
        </div>
      {% else %}
        <div class="alert alert-primary">
          {% blocktrans trimmed %}
            Please
            <a href="{{ edit_bio_url }}">add a speaker biography</a>
            before submitting a talk.
          {% endblocktrans %}
        </div>
      {% endif %}
    {% endblock form_preamble %}
    {% block talkform %}
    <form method="post">
      {% crispy form %}
    </form>
    {% endblock talkform %}
  {% endif %}
</section>
{% endblock %}

wafer/talks/templates/wafer.talks/talks.html
{% extends "wafer/base.html" %}
{% load i18n %}
{% load review %}
{% block title %}{% trans "Talks" %} - {{ WAFER_CONFERENCE_NAME }}{% endblock %}
{% block content %}
<section class="wafer wafer-talks">
  {% block heading %}
    {% if see_all %}
      <h1>{% trans "All Submitted Talks" %}</h1>
    {% elif includes_pending %}
      <h1>{% trans "Planned Talks" %}</h1>
      <div>
        {% blocktrans %}
          This list will include submitted "un-conference" events that have not
          yet been reviewed, accepted, or scheduled.
        {% endblocktrans %}
      </div>
    {% else %}
      <h1>{% trans "Accepted Talks" %}</h1>
    {% endif %}
  {% endblock heading %}
  {% regroup talk_list by talk_type.name as grouped_talks %}
  <div class="table-responsive">
    <table class='table table-striped'>
      {% for type, talks in grouped_talks %}
        <thead class='thead-dark'>
          <tr>
            <th>
               <a href="{% url 'wafer_users_talks' %}?sort={% if sort == 'title' %}default{% else %}title{% endif %}">
                {% if type %}
                  {{ type }}
                {% else %}
                  {% trans "Talk" %}
                {% endif %}
              </a>
            </th>
            {% if tracks %}
              <th>
                 <a href="{% url 'wafer_users_talks' %}?sort={% if sort == 'track' %}default{% else %}track{% endif %}">
                  {% trans "Track" %}
                </a>
              </th>
            {% endif %}
            {% if languages %}
              <th>
                 <a href="{% url 'wafer_users_talks' %}?sort={% if sort == 'lang' %}default{% else %}lang{% endif %}">
                  {% trans "Language" %}
                </a>
              </th>
            {% endif %}
            <th>{% trans "Speakers" %}</th>
          </tr>
        </thead>
        {% for talk in talks %}
          <tr>
            <td>
              {% if not talk.cancelled and not talk.accepted and talk.is_late_submission %}
                <span class="badge bg-warning" title="{% trans 'Late submission' %}">L</span>
              {% endif %}
              {% if talk.submitted %}
                <span class="badge bg-info" title="{% trans 'Submitted' %}">{{ talk.status }}</span>
              {% elif talk.under_consideration %}
                <span class="badge bg-info" title="{% trans 'Under consideration' %}">{{ talk.status }}</span>
              {% elif talk.reject %}
                <span class="badge bg-danger" title="{% trans 'Not accepted' %}">{{ talk.status }}</span>
              {% elif talk.cancelled %}
                <span class="badge bg-warning" title="{% trans 'Talk Cancelled' %}">{{ talk.status }}</span>
              {% elif talk.provisional %}
                <span class="badge bg-success" title="{% trans 'Provisionally Accepted' %}">{{ talk.status }}</span>
              {% endif %}
              {% reviewed_badge user talk %}
              {% if talk.withdrawn %}
                <del><a href="{{ talk.get_absolute_url }}">{{ talk.title }}</a></del>
              {% else %}
                <a href="{{ talk.get_absolute_url }}">{{ talk.title }}</a>
              {% endif %}
            </td>
            {% if tracks %}
              <td>{{ talk.track.name }}</td>
            {% endif %}
            {% if languages %}
              <td>{{ talk.get_language_display }}</td>
            {% endif %}
            <td>
              {% with authors=talk.get_authors_display_name %}
                <span class="author">{{ authors }}</span>
              {% endwith %}
            </td>
          </tr>
        {% endfor %}
      {% empty %}
        <thead class='thead-dark'>
          <tr>
            <th>
              {% trans "Talk" %}
            </th>
            {% if tracks %}<th>{% trans "Track" %}</th>{% endif %}
            {% if languages %}<th>{% trans "Language" %}</th>{% endif %}
            <th>{% trans "Speakers" %}</th>
          </tr>
        </thead>
        <tr>
           <td colspan="{% if tracks and languages %}4{% elif tracks or languages %}3{% else %}2{% endif %}">
            {% trans 'No talks accepted yet.' %}
          </td>
        </tr>
      {% endfor %}
    </table>
  </div>
</section>
{% if is_paginated %}
  <section class="wafer wafer-pagination">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="{% url 'wafer_users_talks_page' page=page_obj.previous_page_number %}?sort={{ sort }}">&laquo;</a></li>
      {% else %}
        <li class="page-item" class="disabled"><a class="page-link" href="#">&laquo;</a></li>
      {% endif %}
      {% for page in paginator.page_range %}
        <li class="page-item"><a class="page-link" href="{% url 'wafer_users_talks_page' page=page %}?sort={{ sort }}">{{ page }}</a></li>
      {% endfor %}
      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="{% url 'wafer_users_talks_page' page=page_obj.next_page_number %}?sort={{ sort }}">&raquo;</a></li>
      {% else %}
        <li class="page-item" class="disabled"><a class="page-link" href="#">&raquo;</a></li>
      {% endif %}
    </ul>
  </section>
{% endif %}
{% endblock %}