wafer/sponsors/urls.py
from django.urls import re_path, include
from rest_framework import routers

from wafer.sponsors.views import (
    ShowSponsors, SponsorView, ShowPackages, SponsorViewSet, PackageViewSet)


router = routers.DefaultRouter()
router.register(r'sponsors', SponsorViewSet)
router.register(r'packages', PackageViewSet)

urlpatterns = [
    re_path(r'^$', ShowSponsors.as_view(),
        name='wafer_sponsors'),
    re_path(r'^(?P<pk>\d+)/$', SponsorView.as_view(), name='wafer_sponsor'),
    re_path(r'^packages/$', ShowPackages.as_view(),
        name='wafer_sponsorship_packages'),
    re_path(r'^api/', include(router.urls)),
]

wafer/urls.py
from django.urls import include, re_path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    re_path(r'^accounts/', include('wafer.registration.urls')),
    re_path(r'^users/', include('wafer.users.urls')),
    re_path(r'^talks/', include('wafer.talks.urls')),
    re_path(r'^sponsors/', include('wafer.sponsors.urls')),
    re_path(r'^pages/', include('wafer.pages.urls')),
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^markitup/', include('markitup.urls')),
    re_path(r'^schedule/', include('wafer.schedule.urls')),
    re_path(r'^tickets/', include('wafer.tickets.urls')),
    re_path(r'^kv/', include('wafer.kv.urls')),
]

# Serve media
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Pages occupy the entire URL space, and must come last
urlpatterns.append(re_path(r'', include('wafer.pages.urls')))

wafer/sponsors/models.py
# -*- coding: utf-8 -*-

import logging

from django.core.validators import MinValueValidator
from django.db import models
from django.db.models.signals import post_save
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from markitup.fields import MarkupField

from wafer.menu import menu_logger, refresh_menu_cache

logger = logging.getLogger(__name__)


class File(models.Model):
    """A file for use in sponsor and sponshorship package descriptions."""
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    item = models.FileField(upload_to='sponsors_files')

    def __str__(self):
        return u'%s (%s)' % (self.name, self.item.url)


class SponsorshipPackage(models.Model):
    """A description of a sponsorship package."""
    order = models.IntegerField(default=1)
    name = models.CharField(max_length=255)
    number_available = models.IntegerField(
        null=True, validators=[MinValueValidator(0)])
    currency = models.CharField(
        max_length=16, default='$',
        help_text=_("Currency symbol for the sponsorship amount."))
    price = models.DecimalField(
        max_digits=12, decimal_places=2,
        help_text=_("Amount to be sponsored."))
    short_description = models.TextField(
        help_text=_("One sentence overview of the package."))
    description = MarkupField(
        help_text=_("Describe what the package gives the sponsor."))
    files = models.ManyToManyField(
        File, related_name="packages", blank=True,
        help_text=_("Images and other files for use in"
                    " the description markdown field."))
    # We use purely ascii help text, to avoid issues with the migrations
    # not handling unicode help text nicely.
    symbol = models.CharField(
        max_length=1, blank=True,
        help_text=_("Optional symbol to display in the sponsors list "
                    "next to sponsors who have taken this package, "
                    "(for example *)."))

    class Meta:
        ordering = ['order', '-price', 'name']

    def __str__(self):
        return u'%s (amount: %.0f)' % (self.name, self.price)

    def number_claimed(self):
        return self.sponsors.count()


class Sponsor(models.Model):
    """A conference sponsor."""
    order = models.IntegerField(default=1)
    name = models.CharField(max_length=255)
    packages = models.ManyToManyField(SponsorshipPackage,
                                      related_name="sponsors")
    description = MarkupField(
        help_text=_("Write some nice things about the sponsor."))
    url = models.URLField(
        default="", blank=True,
        help_text=_("URL to link back to the sponsor if required"))

    class Meta:
        ordering = ['order', 'name', 'id']

    def __str__(self):
        return u'%s' % (self.name,)

    def get_absolute_url(self):
        return reverse('wafer_sponsor', args=(self.pk,))

    def symbols(self):
        """Return a string of the symbols of all the packages this sponsor has
           taken."""
        packages = self.packages.all()
        symbols = u"".join(p.symbol for p in packages)
        return symbols

    @property
    def symbol(self):
        """The symbol of the highest level package this sponsor has taken."""
        package = self.packages.first()
        if package:
            return package.symbol
        return u""


class TaggedFile(models.Model):
    """Tags for files associated with a given sponsor"""
    tag_name = models.CharField(max_length=255, null=False)
    tagged_file = models.ForeignKey(File, on_delete=models.CASCADE)
    sponsor = models.ForeignKey(Sponsor, related_name="files",
                                on_delete=models.CASCADE)


def sponsor_menu(
        root_menu, menu="sponsors", label=_("Sponsors"),
        sponsors_item=_("Our sponsors"),
        packages_item=_("Sponsorship packages")):
    """Add sponsor menu links."""
    if not SponsorshipPackage.objects.exists():
        return
    root_menu.add_menu(menu, label, items=[])
    added_to_menu = set()
    for sponsor in (
            Sponsor.objects.all()
            .order_by('packages', 'order', 'id')
            .prefetch_related('packages')):
        if sponsor in added_to_menu:
            # We've already added this in a previous packaged
            continue
        added_to_menu.add(sponsor)
        symbols = sponsor.symbols()
        if symbols:
            item_name = u"» %s %s" % (sponsor.name, symbols)
        else:
            item_name = u"» %s" % (sponsor.name,)
        with menu_logger(logger, "sponsor %r" % (sponsor.name,)):
            root_menu.add_item(
                item_name, sponsor.get_absolute_url(), menu=menu)

    if sponsors_item:
        with menu_logger(logger, "sponsors page link"):
            root_menu.add_item(
                sponsors_item, reverse("wafer_sponsors"), menu)
    if packages_item:
        with menu_logger(logger, "sponsorship package page link"):
            root_menu.add_item(
                packages_item, reverse("wafer_sponsorship_packages"), menu)


post_save.connect(refresh_menu_cache, sender=Sponsor)

wafer/sponsors/views.py
from bakery.views import BuildableListView, BuildableDetailView
from rest_framework import viewsets
from rest_framework.permissions import DjangoModelPermissionsOrAnonReadOnly

from wafer.sponsors.models import Sponsor, SponsorshipPackage
from wafer.sponsors.serializers import SponsorSerializer, PackageSerializer


class ShowSponsors(BuildableListView):
    template_name = 'wafer.sponsors/sponsors.html'
    model = Sponsor
    build_path = 'sponsors/index.html'

    def get_queryset(self):
        return Sponsor.objects.all().order_by('packages', 'order', 'id')


class SponsorView(BuildableDetailView):
    template_name = 'wafer.sponsors/sponsor.html'
    model = Sponsor


class ShowPackages(BuildableListView):
    template_name = 'wafer.sponsors/packages.html'
    model = SponsorshipPackage
    build_path = 'sponsors/packages/index.html'


class SponsorViewSet(viewsets.ModelViewSet):
    """API endpoint for users."""
    queryset = Sponsor.objects.all()
    serializer_class = SponsorSerializer
    permission_classes = (DjangoModelPermissionsOrAnonReadOnly, )


class PackageViewSet(viewsets.ModelViewSet):
    """API endpoint for users."""
    queryset = SponsorshipPackage.objects.all()
    serializer_class = PackageSerializer
    permission_classes = (DjangoModelPermissionsOrAnonReadOnly, )

wafer/sponsors/templates/wafer.sponsors/packages.html
{% extends "wafer/base.html" %}
{% load i18n %}
{% block content %}
<section class="wafer wafer-sponsorship-packages">
  {% block page_title %}
  <h1>{% trans 'Sponsorship Packages' %}</h1>
  {% endblock %}
  {% block pre_package_list %}{% endblock %}
  {% block package_list %}
    <div class="wafer list">
      {% for package in sponsorshippackage_list %}
        {% block package_display %}
          <section class="wafer wafer-sponsorship-package
                          wafer-sponsor-{{ package.name.lower }}">
            <div class="card">
              <div class="card-body">
                <h2 class="card-title">
                  {% if package.symbol %}
                    {{ package.symbol }}
                  {% endif %}
                  {{ package.name }} ({{ package.currency }} {{ package.price|floatformat:0 }})
                </h2>
                {% if package.number_available %}
                  <p>{% trans 'Total number available:' %} {{ package.number_available }}</p>
                {% endif %}
                <p>{% trans 'Packages claimed:' %} {{ package.number_claimed }}</p>
                <p>{{ package.short_description }}</p>
                {{ package.description }}
              </div>
            </div>
          </section>
        {% endblock package_display %}
      {% empty %}
        <p>{% trans 'No sponsorship packages available yet.' %}</p>
      {% endfor %}
    </div>
  {% endblock package_list %}
  {% block post_package_list %}{% endblock %}
</section>
{% endblock content %}

wafer/sponsors/templates/wafer.sponsors/sponsor.html
{% extends "wafer/base.html" %}
{% load i18n %}
{% load sponsors %}
{% block content %}
<section class="wafer wafer-sponsor">
  <h1>
    {% if object.url %}
      <a href="{{ object.url }}">{{ object.name }}</a>
    {% else %}
      {{ object.name }}
    {% endif %}
  </h1>
  <div class="sponsor-detail">
    {% sponsor_tagged_image object "main_logo" as logo_url %}
    {% if logo_url != '' %}
      <div style="float: right; margin-left:5px;">
        <a href="{{ object.url }}">
          <img style="background: white; max-width:400px; max-height:200px;" src="{{ logo_url }}">
        </a>
      </div>
    {% endif %}
    {{ object.description }}
  </div>
</section>
{% endblock %}

wafer/sponsors/templates/wafer.sponsors/sponsors.html
{% extends "wafer/base.html" %}
{% load i18n %}
{% load sponsors %}
{% block title %}{% trans "Sponsors" %} - {{ WAFER_CONFERENCE_NAME }}{% endblock %}
{% block content %}
<section class="wafer wafer-sponsors">
  {% block page_title %}
  <h1>{% trans 'Sponsors' %}</h1>
  {% endblock %}
  {% block pre_sponsor_list %}{% endblock %}
  {% block sponsor_list %}
    <div class="wafer list">
      {% for sponsor in sponsor_list %}
        {% block sponsor_details %}
          <section class="wafer wafer-sponsor
                          wafer-sponsor-{{ sponsor.packages.first.name.lower }}">
            <div class="card">
              <div class="card-body">
                <h2 class="card-title">
                  {% if sponsor.symbol %}
                    {{ sponsor.symbol }}
                  {% endif %}
                  {% if sponsor.url %}
                    <a href="{{ sponsor.url }}">{{ sponsor.name }}</a>
                  {% else %}
                    {{ sponsor.name }}
                  {% endif %}
                  <small class="text-right">{{ sponsor.packages.first.name }}</small>
                </h2>
                {% sponsor_tagged_image sponsor "main_logo" as logo_url %}
                {% if logo_url != '' %}
                  <div style="float: right; margin-left:5px;">
                    <a href="{{ sponsor.url }}">
                      <img style="background: white; max-width:400px; max-height:200px;" src="{{ logo_url }}">
                    </a>
                  </div>
                {% endif %}
                {{ sponsor.description }}
              </div>
            </div>
            <hr>
          </section>
        {% endblock sponsor_details %}
      {% empty %}
        <p>{% trans 'No sponsors yet.' %}</p>
      {% endfor %}
    </div>
  {% endblock sponsor_list %}
  {% block post_sponsor_list %}{% endblock %}
</section>
{% endblock content %}

wafer/sponsors/templates/wafer.sponsors/sponsors_block.html
{% load sponsors %}
<div id="wafer-sponsors" class="container">
  {% for package in packages %}
    {% if package.sponsors.exists %}
      <div>
        <div class="package">{{ package.name }}</div>
        <ul>
          {% for sponsor in package.sponsors.all %}
            <li>
              {% sponsor_tagged_image sponsor "main_logo" as logo_url %}
              {% if logo_url != '' %}
                <img src="{{ logo_url }}"
                     alt="{{ sponsor.name }}"
                     style="background: white; max-width: 400px; max-height:200px;"
                     title="{{ sponsor.name }}">
              {% else %}
                <span class="nologo">{{ sponsor.name }}</span>
              {% endif %}
            </li>
          {% endfor %}
        </ul>
      </div>
    {% endif %}
  {% endfor %}
</div>

wafer/sponsors/templates/wafer.sponsors/sponsors_footer.html
{% load sponsors %}
<div id="wafer-sponsors" class="container">
  {% for package in packages %}
    {% if package.sponsors.exists %}
      {% for sponsor in package.sponsors.all %}
        {% sponsor_tagged_image sponsor "footer_logo" as logo_url %}
          {% spaceless %}
          <a href="{{ sponsor.url }}">
            {% if logo_url != '' %}
              <img src="{{ logo_url }}"
                   alt="{{ sponsor.name }}"
                   style="max-width: 200px; max-height:100px;"
                   title="{{ sponsor.name }}">
            {% else %}
              <span class="nologo">{{ sponsor.name }}</span>
            {% endif %}
          </a>
          {% endspaceless %}
      {% endfor %}
      <br>
    {% endif %}
  {% endfor %}
</div>